# Generated by Django 4.2.7 on 2025-08-26 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TriangulationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("accuracy_meters", models.FloatField()),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("gps", "GPS Nativo"),
                            ("cell_triangulation", "Triangulação Celular"),
                            ("ip_fallback", "Localização por IP"),
                        ],
                        max_length=50,
                    ),
                ),
                ("towers_used", models.IntegerField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("processing_time_ms", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CellTowerReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operator", models.CharField(max_length=50)),
                ("cell_id", models.CharField(max_length=20)),
                ("lac", models.CharField(max_length=20)),
                ("rssi", models.IntegerField()),
                ("distance_meters", models.FloatField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="towers",
                        to="triangulacao.triangulationsession",
                    ),
                ),
            ],
        ),
    ]
