# Generated by Django 4.2.7 on 2025-08-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioAgricola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('mes_inicio', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('mes_fim', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('regiao_aplicavel', models.CharField(blank=True, max_length=100)),
                ('importancia', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaRecomendacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioRecomendacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_comentario', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['data_comentario'],
            },
        ),
        migrations.CreateModel(
            name='LikeRecomendacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_like', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerguntaChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('resposta', models.TextField()),
                ('categoria_pergunta', models.CharField(choices=[('cultivo', 'Cultivo'), ('pragas', 'Pragas e Doenças'), ('clima', 'Clima'), ('irrigacao', 'Irrigação'), ('adubacao', 'Adubação'), ('colheita', 'Colheita'), ('mercado', 'Mercado'), ('outros', 'Outros')], default='outros', max_length=50)),
                ('satisfacao', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Avaliação de 1 a 5', null=True)),
                ('data_pergunta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('epoca_aplicacao', models.CharField(choices=[('pre_plantio', 'Pré-plantio'), ('plantio', 'Plantio'), ('crescimento', 'Crescimento'), ('floracao', 'Floração'), ('frutificacao', 'Frutificação'), ('colheita', 'Colheita'), ('pos_colheita', 'Pós-colheita'), ('qualquer', 'Qualquer época')], default='qualquer', max_length=20)),
                ('nivel_dificuldade', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil')], default='facil', max_length=10)),
                ('custo_estimado', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], default='baixo', max_length=10)),
                ('tempo_implementacao', models.CharField(blank=True, max_length=100)),
                ('materiais_necessarios', models.TextField(blank=True)),
                ('passos_implementacao', models.JSONField(default=list)),
                ('beneficios_esperados', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('visualizacoes', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
