# Generated by Django 4.2.7 on 2025-08-20 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recomendacoes', '0001_initial'),
        ('pragas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacao',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recomendacao',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendacoes.categoriarecomendacao'),
        ),
        migrations.AddField(
            model_name='recomendacao',
            name='culturas_aplicaveis',
            field=models.ManyToManyField(blank=True, to='pragas.cultura'),
        ),
        migrations.AddField(
            model_name='recomendacao',
            name='likes',
            field=models.ManyToManyField(related_name='recomendacoes_curtidas', through='recomendacoes.LikeRecomendacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perguntachatbot',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likerecomendacao',
            name='recomendacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendacoes.recomendacao'),
        ),
        migrations.AddField(
            model_name='likerecomendacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentariorecomendacao',
            name='recomendacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='recomendacoes.recomendacao'),
        ),
        migrations.AddField(
            model_name='comentariorecomendacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendarioagricola',
            name='cultura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pragas.cultura'),
        ),
        migrations.AlterUniqueTogether(
            name='likerecomendacao',
            unique_together={('usuario', 'recomendacao')},
        ),
    ]
