# Generated by Django 4.2.7 on 2025-09-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recomendacoes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perguntachatbot",
            name="categoria_pergunta",
            field=models.CharField(
                choices=[
                    ("cultivo", "Cultivo"),
                    ("pragas", "Pragas e Doenças"),
                    ("clima", "Clima"),
                    ("irrigacao", "Rega"),
                    ("adubacao", "Adubação"),
                    ("colheita", "Colheita"),
                    ("mercado", "Mercado"),
                    ("outros", "Outros"),
                ],
                default="outros",
                max_length=50,
            ),
        ),
    ]
