# Generated by Django 4.2.7 on 2025-08-20 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_alvo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_alerta', models.CharField(choices=[('acima', 'Preço Acima de'), ('abaixo', 'Preço Abaixo de'), ('mudanca', 'Mudança Significativa')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_notificacao', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemandaMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_demanda', models.CharField(choices=[('muito_baixa', 'Muito Baixa'), ('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('muito_alta', 'Muito Alta')], max_length=20)),
                ('quantidade_demandada', models.FloatField(help_text='Quantidade em unidades do produto')),
                ('periodo_demanda', models.CharField(max_length=100)),
                ('preco_sugerido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contato_comprador', models.CharField(blank=True, max_length=200)),
                ('requisitos_qualidade', models.TextField(blank=True)),
                ('data_necessidade', models.DateField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('localizacao', models.CharField(max_length=200)),
                ('provincia', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('tipo_mercado', models.CharField(choices=[('local', 'Mercado Local'), ('regional', 'Mercado Regional'), ('grossista', 'Mercado Grossista'), ('exportacao', 'Mercado de Exportação')], max_length=20)),
                ('contato', models.CharField(blank=True, max_length=200)),
                ('horario_funcionamento', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrecoMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qualidade', models.CharField(choices=[('primeira', 'Primeira Qualidade'), ('segunda', 'Segunda Qualidade'), ('terceira', 'Terceira Qualidade'), ('exportacao', 'Qualidade Exportação')], default='primeira', max_length=20)),
                ('disponibilidade', models.CharField(choices=[('abundante', 'Abundante'), ('normal', 'Normal'), ('escasso', 'Escasso'), ('indisponivel', 'Indisponível')], default='normal', max_length=20)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('fonte_informacao', models.CharField(blank=True, max_length=200)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoAgricola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variedade', models.CharField(blank=True, max_length=100)),
                ('unidade_medida', models.CharField(choices=[('kg', 'Quilograma'), ('ton', 'Tonelada'), ('saca', 'Saca'), ('caixa', 'Caixa'), ('unidade', 'Unidade')], default='kg', max_length=20)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TendenciaMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(max_length=200)),
                ('tendencia', models.CharField(choices=[('alta', 'Tendência de Alta'), ('baixa', 'Tendência de Baixa'), ('estavel', 'Estável'), ('volatil', 'Volátil')], max_length=20)),
                ('preco_medio_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_medio_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variacao_percentual', models.FloatField()),
                ('periodo_analise', models.CharField(max_length=50)),
                ('fatores_influencia', models.TextField(blank=True)),
                ('previsao_proximos_30_dias', models.TextField(blank=True)),
                ('data_analise', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.produtoagricola')),
            ],
        ),
    ]
