# Generated by Django 4.2.7 on 2025-08-20 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pragas', '0001_initial'),
        ('mercado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoagricola',
            name='cultura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pragas.cultura'),
        ),
        migrations.AddField(
            model_name='precomercado',
            name='mercado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.mercado'),
        ),
        migrations.AddField(
            model_name='precomercado',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.produtoagricola'),
        ),
        migrations.AddField(
            model_name='demandamercado',
            name='mercado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.mercado'),
        ),
        migrations.AddField(
            model_name='demandamercado',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.produtoagricola'),
        ),
        migrations.AddField(
            model_name='alertapreco',
            name='mercado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mercado.mercado'),
        ),
        migrations.AddField(
            model_name='alertapreco',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.produtoagricola'),
        ),
    ]
