# Generated by Django 4.2.7 on 2025-08-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampanhaNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('titulo_template', models.CharField(max_length=200)),
                ('conteudo_template', models.TextField()),
                ('canais', models.JSONField(default=list)),
                ('filtros_usuario', models.JSONField(blank=True, default=dict)),
                ('data_agendamento', models.DateTimeField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=False)),
                ('total_envios', models.IntegerField(default=0)),
                ('total_sucessos', models.IntegerField(default=0)),
                ('total_falhas', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_execucao', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tentativa', models.IntegerField()),
                ('status_tentativa', models.CharField(max_length=20)),
                ('resposta_api', models.TextField(blank=True)),
                ('codigo_resposta', models.CharField(blank=True, max_length=10)),
                ('tempo_resposta', models.FloatField(blank=True, null=True)),
                ('data_tentativa', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('canal', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('push', 'Push Notification'), ('app', 'In-App')], max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviada', 'Enviada'), ('falhada', 'Falhada'), ('entregue', 'Entregue'), ('lida', 'Lida')], default='pendente', max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20)),
                ('agendada_para', models.DateTimeField(blank=True, null=True)),
                ('tentativas_envio', models.IntegerField(default=0)),
                ('ultima_tentativa', models.DateTimeField(blank=True, null=True)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('data_leitura', models.DateTimeField(blank=True, null=True)),
                ('erro_envio', models.TextField(blank=True)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='PreferenciaNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receber_clima', models.BooleanField(default=True)),
                ('receber_pragas', models.BooleanField(default=True)),
                ('receber_mercado', models.BooleanField(default=True)),
                ('receber_recomendacoes', models.BooleanField(default=True)),
                ('receber_alertas_urgentes', models.BooleanField(default=True)),
                ('horario_inicio', models.TimeField(default='07:00')),
                ('horario_fim', models.TimeField(default='19:00')),
                ('canal_clima', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('push', 'Push Notification'), ('app', 'In-App')], default='sms', max_length=20)),
                ('canal_pragas', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('push', 'Push Notification'), ('app', 'In-App')], default='sms', max_length=20)),
                ('canal_mercado', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('push', 'Push Notification'), ('app', 'In-App')], default='sms', max_length=20)),
                ('canal_recomendacoes', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('push', 'Push Notification'), ('app', 'In-App')], default='app', max_length=20)),
                ('frequencia_clima', models.CharField(choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('importantes', 'Apenas Importantes')], default='importantes', max_length=20)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('template_sms', models.TextField(blank=True)),
                ('template_whatsapp', models.TextField(blank=True)),
                ('template_email', models.TextField(blank=True)),
                ('template_push', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
