# Generated by Django 4.2.7 on 2025-08-20 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencianotificacao',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_notificacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacoes.tiponotificacao'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logenvio',
            name='notificacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_envio', to='notificacoes.notificacao'),
        ),
        migrations.AddField(
            model_name='campanhanotificacao',
            name='criada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanhas_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campanhanotificacao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacoes.tiponotificacao'),
        ),
        migrations.AddField(
            model_name='campanhanotificacao',
            name='usuarios_alvo',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
