# Generated by Django 4.2.7 on 2025-09-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notificacoes", "0003_alertsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertsubscription",
            name="canal",
            field=models.CharField(
                choices=[("sms", "SMS"), ("whatsapp", "WhatsApp")],
                default="sms",
                max_length=20,
            ),
        ),
    ]
