# Generated by Django 4.2.7 on 2025-08-20 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('nome_cientifico', models.CharField(blank=True, max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('epoca_plantio', models.CharField(blank=True, max_length=200)),
                ('tempo_colheita', models.IntegerField(blank=True, help_text='Dias até colheita', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeteccaoPraga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='deteccoes_pragas/')),
                ('resultado_ia', models.JSONField(blank=True, null=True)),
                ('confianca_deteccao', models.FloatField(blank=True, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=200)),
                ('observacoes_usuario', models.TextField(blank=True)),
                ('verificado_por_especialista', models.BooleanField(default=False)),
                ('data_deteccao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoControle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_controle', models.CharField(choices=[('biologico', 'Controle Biológico'), ('quimico', 'Controle Químico'), ('cultural', 'Controle Cultural'), ('mecanico', 'Controle Mecânico'), ('integrado', 'Manejo Integrado')], max_length=20)),
                ('descricao', models.TextField()),
                ('produtos_recomendados', models.TextField(blank=True)),
                ('custo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('eficacia', models.IntegerField(blank=True, help_text='Eficácia de 1-10', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPraga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_cientifico', models.CharField(blank=True, max_length=200)),
                ('tipo', models.CharField(choices=[('inseto', 'Inseto'), ('fungo', 'Fungo'), ('bacteria', 'Bactéria'), ('virus', 'Vírus'), ('nematoide', 'Nematóide'), ('erva_daninha', 'Erva Daninha')], max_length=20)),
                ('descricao', models.TextField()),
                ('sintomas', models.TextField()),
                ('culturas_afetadas', models.ManyToManyField(to='pragas.cultura')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('nivel_infestacao', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto'), ('severo', 'Severo')], max_length=10)),
                ('area_afetada', models.FloatField(help_text='Área em hectares')),
                ('data_primeira_observacao', models.DateField()),
                ('descricao', models.TextField()),
                ('fotos', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('controlado', 'Controlado'), ('resolvido', 'Resolvido')], default='ativo', max_length=20)),
                ('data_relatorio', models.DateTimeField(auto_now_add=True)),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pragas.cultura')),
                ('praga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pragas.tipopraga')),
            ],
        ),
    ]
