# Generated by Django 4.2.7 on 2025-08-20 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pragas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorioocorrencia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metodocontrole',
            name='praga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_controle', to='pragas.tipopraga'),
        ),
        migrations.AddField(
            model_name='deteccaopraga',
            name='cultura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pragas.cultura'),
        ),
        migrations.AddField(
            model_name='deteccaopraga',
            name='especialista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verificacoes_praga', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deteccaopraga',
            name='praga_detectada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pragas.tipopraga'),
        ),
        migrations.AddField(
            model_name='deteccaopraga',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
