# Generated by Django 4.2.7 on 2025-09-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pragas", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metodocontrole",
            name="tipo_controle",
            field=models.CharField(
                choices=[
                    ("biologico", "Controle Biológico"),
                    ("quimico", "Controle Químico"),
                    ("cultural", "Controle Cultural"),
                    ("mecanico", "Controle Mecânico"),
                    ("integrado", "Maneio Integrado"),
                ],
                max_length=20,
            ),
        ),
    ]
