# Generated by Django 4.2.7 on 2025-08-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaClimatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('chuva_forte', 'Chuva Forte'), ('seca', 'Seca'), ('tempestade', 'Tempestade'), ('ciclone', 'Ciclone'), ('geada', 'Geada'), ('calor_extremo', 'Calor Extremo')], max_length=20)),
                ('nivel', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto'), ('critico', 'Crítico')], max_length=10)),
                ('localizacao', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrevisaoClimatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('data_previsao', models.DateField()),
                ('temperatura_min', models.FloatField()),
                ('temperatura_max', models.FloatField()),
                ('umidade', models.IntegerField()),
                ('precipitacao', models.FloatField(default=0.0)),
                ('velocidade_vento', models.FloatField()),
                ('condicao_clima', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('fonte_dados', models.CharField(default='OpenWeather', max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['data_previsao'],
                'unique_together': {('localizacao', 'data_previsao')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoClima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('temperatura_media', models.FloatField()),
                ('precipitacao_total', models.FloatField()),
                ('umidade_media', models.IntegerField()),
                ('fonte_dados', models.CharField(max_length=50)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('localizacao', 'data')},
            },
        ),
    ]
