# Generated by Django 4.2.7 on 2025-12-05 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("plantio", "Plantio"),
                            ("adubo", "Adubação"),
                            ("defensivo", "Aplicação Defensivo"),
                            ("capina", "Capina"),
                            ("irrigacao", "Irrigação"),
                            ("inspecao", "Inspeção"),
                            ("colheita", "Colheita"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descricao", models.TextField()),
                ("data", models.DateField()),
                (
                    "custo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "nota_voz",
                    models.FileField(blank=True, null=True, upload_to="notas_voz/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-data", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("cultura", models.CharField(max_length=100)),
                ("area_hectares", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_plantio", models.DateField()),
                ("data_colheita_estimada", models.DateField()),
                (
                    "orcamento_total",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planejamento", "Planejamento"),
                            ("ativo", "Em Andamento"),
                            ("colhido", "Colhido"),
                            ("vendido", "Vendido"),
                        ],
                        default="planejamento",
                        max_length=20,
                    ),
                ),
                ("localizacao_gps", models.CharField(blank=True, max_length=100)),
                (
                    "foto_capa",
                    models.ImageField(blank=True, null=True, upload_to="projetos/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fase_atual", models.CharField(max_length=50)),
                ("progresso_percent", models.IntegerField(default=0)),
                ("dias_decorridos", models.IntegerField(default=0)),
                ("dias_restantes", models.IntegerField(default=0)),
                ("saude_score", models.FloatField(default=0)),
                ("rendimento_estimado", models.FloatField(default=0)),
                ("alertas_json", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard",
                        to="projetos.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FieldPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="campo_fotos/")),
                ("analise_ia_json", models.JSONField(default=dict)),
                ("gps_coords", models.CharField(blank=True, max_length=100)),
                ("data_captura", models.DateTimeField(auto_now_add=True)),
                (
                    "atividade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="projetos.fieldactivity",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="fieldactivity",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="atividades",
                to="projetos.project",
            ),
        ),
        migrations.CreateModel(
            name="CostTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("insumo", "Insumos"),
                            ("mao_obra", "Mão de Obra"),
                            ("maquina", "Maquinário"),
                            ("transporte", "Transporte"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descricao", models.CharField(max_length=200)),
                ("valor_orcado", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "valor_real",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("data", models.DateField()),
                (
                    "nota_fiscal",
                    models.ImageField(
                        blank=True, null=True, upload_to="notas_fiscais/"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custos",
                        to="projetos.project",
                    ),
                ),
            ],
        ),
    ]
