# Generated by Django 4.2.7 on 2025-09-10 18:45

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_relax_canal_preferido_nullable'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Check if tipos_alertas column exists and has NOT NULL constraint
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 
                    FROM information_schema.columns 
                    WHERE table_name = 'users_user' 
                    AND column_name = 'tipos_alertas'
                    AND table_schema = 'public'
                ) THEN
                    -- Update existing NULL values to empty array
                    UPDATE users_user SET tipos_alertas = '[]'::jsonb WHERE tipos_alertas IS NULL;
                    
                    -- Drop NOT NULL constraint if it exists
                    IF EXISTS (
                        SELECT 1 
                        FROM information_schema.columns 
                        WHERE table_name = 'users_user' 
                        AND column_name = 'tipos_alertas' 
                        AND is_nullable = 'NO'
                        AND table_schema = 'public'
                    ) THEN
                        ALTER TABLE users_user ALTER COLUMN tipos_alertas DROP NOT NULL;
                    END IF;
                END IF;
            END
            $$;
            """,
            reverse_sql="""
            -- Reverse migration: restore NOT NULL constraint if column exists
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 
                    FROM information_schema.columns 
                    WHERE table_name = 'users_user' 
                    AND column_name = 'tipos_alertas'
                    AND table_schema = 'public'
                ) THEN
                    -- Ensure no NULL values exist before adding constraint
                    UPDATE users_user SET tipos_alertas = '[]'::jsonb WHERE tipos_alertas IS NULL;
                    ALTER TABLE users_user ALTER COLUMN tipos_alertas SET NOT NULL;
                END IF;
            END
            $$;
            """
        ),
    ]
